title: hemisus
description: "hemisus blog"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.jpg"

# Social Links
email: hydro6323@gmail.com
github_username: hemisus
instagram_username: hemisus_

# External API
giscus_repo: "hemisus/hemisus.github.io"
giscus_repoId: "R_kgDOSj23SQ"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOSj23Sc4C9puT"
goatcounter_code: hemisus
google_analytics:
naver_site_vertification: af75ef8403e04c3113c162eb9eba86e2d7803819
# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
